name: Checks
on:
  pull_request:
    types: [closed] 
    #[opened, synchronize]
    branches:
      - dev

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # - name: "Setup npm"
    #   run: |
    #     npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
    #     npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

    - name: Install dependencies
      run: |
        npx lerna bootstrap

    - name: Run build
      run: npx lerna run build

    - name: Run test
      run: npx lerna run test
