name: Checks
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Use NodeJS 16"
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npx lerna bootstrap
    - name: Run Build
      run: npx lerna run build

    - name: Run Test
      run: npx lerna run test