name: Publish
env:
  USER_EMAIL: ${{ secrets.LIBRARY_USER_EMAIL }}
  USER_NAME: ${{ secrets.LIBRARY_USER_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Set git config
      #   run: |
      #     git config --global credential.helper cache
      #     git config --global user.email ${USER_EMAIL}
      #     git config --global user.name ${USER_NAME}
      #   env:
      #     GITHUB_TOKEN: ${GITHUB_TOKEN}

      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npx lerna bootstrap

      - name: Version Bump
        run: |
          npx lerna version --conventional-commits --conventional-graduate --yes

      - name: Publish packages
        run: |
          npx lerna publish from-package --yes
          # npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${NPM_TOKEN}
