name: Publish On NPMJS
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set Git Config
        run: |
          git config --global user.email "ci-build@aemforms"
          git config --global user.name "ci-build"
        env:
          GITHUB_TOKEN: ${{ secrets.ADOBE_BOT_GH_TOKEN }}
          GH_TOKEN: ${{ secrets.ADOBE_BOT_GH_TOKEN }}

      - name: Use NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npx lerna bootstrap
      
      - name: Authenticate with Registry
        run: |
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami        
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version & Publish Packages
        run: |
          npx lerna publish patch --no-private --conventional-commits --conventional-graduate --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
