name: Publish On NPMJS

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Set Git Config
        run: |
          git config --global user.email "ci-build@aemforms"
          git config --global user.name "ci-build"
        env:
          GITHUB_TOKEN: ${{ secrets.ADOBE_GH_TOKEN }}

      - name: Install Dependencies
        run: |
          npm install
          npx lerna bootstrap

      - name: Run Build
        run: |
          npx lerna run build
          
      - name: Authenticate with NPM Registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version & Publish "react-vanilla-components"
        run: |
          npx lerna publish patch --no-private --conventional-commits --conventional-graduate --yes --scope react-vanilla-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
