name: Publish
env:
  USER_EMAIL: ${{ secrets.LIBRARY_USER_EMAIL }}
  USER_NAME: ${{ secrets.LIBRARY_USER_NAME }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_REPOSITORY: ${{ secrets.GH_REPOSITORY }} 
on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      
permissions:
  contents: write # for checkout and tag
  pull-requests: write  # for comments
  packages: write # for publish

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0

      - name: Set Git Config
        run: |
          git config --global user.name ${USER_NAME}
          git config --global user.email ${USER_EMAIL}
          # git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        env:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
          GH_TOKEN: ${GITHUB_TOKEN}
          GITHUB_PAT: ${GITHUB_TOKEN}

      - name: Use NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # - name: Install Dependencies
      #   run: |
      #     npx lerna bootstrap

      # - name: Run build
      #   run: |
      #     npx lerna run build

      - name: Version & Publish Packages
        run: |
          npx lerna publish patch from-package --yes
          # npx lerna publish patch --no-private --yes
          # npx lerna version --conventional-commits --conventional-graduate --yes
        env:
          NODE_AUTH_TOKEN: ${NPM_TOKEN}
